name = "coffee-qr"
pages_build_output_dir = "./public"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "coffee-qr"
database_id = "REPLACE_WITH_ID_FROM_wrangler_d1_create"
