# "name" must match the Worker name in the Cloudflare dashboard.
name = "frendly-phishing"
main = "src/index.js"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "coffee-qr"
database_id = "15d79728-3797-4714-84f1-acb15681a14f"
